### ISSUE TITLE
Persistent GPU memory errors

### ISSUE THREAD

**Issue by timFinn** [stereolabs/zed-unreal-examples#1]
I'm working with the L_Passthrough project and I can't seem to find a way to provide Unreal with a sufficient amount of GPU memory. I have the same issue on two different machines, one with an 8GB card and another with 16GB. No clear reason as to why it might be lacking resources and Task Manager doesn't show any other applications consuming extraordinary amount of GPU memory? Is there something I can do to allocate more GPU memory to Unreal? Simply executing again will yield a positive result, but this is both frustrating and time consuming. TIA.

**Comment by ThomasBourbon** [comment]
Hi TimFinn
Indeed this is a known issue when using the Zed Unreal Plugin. It's still in our backlog since it's not blocking and limited to Unreal Editor use, but as you said it's very frustrating and happens quite often when developing.
The issue seems to come from the interaction between Unreal Editor and our SDK, thus I don't think you can do something on your side to fix it.
I'll keep you updated, we should work on this soon.
